### ISSUE TITLE
Constant crash when using LiveTV and recordings

### ISSUE THREAD

**Issue by MichaelAnders** [FernetMenta/vdr-plugin-vnsiserver#88]
Hi,

I'm unable to watch Live TV (libreelec) when I have recordings going on at the same time (4 DVB-S2 cards in use). 

Using GDB and latest git code the problem occurs here, each and every time:
Thread 13 (Thread 0x7fffd37fe700 (LWP 31478)):
#0  0x00007ffff62f49e3 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff4901d4d in cVNSIServer::Action (this=0x8cf650) at vnsiserver.c:195
#2  0x00000000005136f9 in cThread::StartThread (Thread=0x8cf650) at thread.c:262
#3  0x00007ffff79686ba in start_thread (arg=0x7fffd37fe700) at pthread_create.c:333
#4  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Entire bt:
Thread 13 "VNSI Server" hit Catchpoint 1 (signal SIG32), 0x00007ffff62f49e3 in select () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: Datei oder Verzeichnis nicht gefunden.

Thread 13 "VNSI Server" hit Catchpoint 1 (signal SIG32), 0x00007ffff62f49e3 in select () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: Datei oder Verzeichnis nicht gefunden.
(gdb) thread apply all bt

Thread 37 (Thread 0x7fffab7fe700 (LWP 32079)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff63104ce in __poll_chk (fds=<optimized out>, nfds=<optimized out>, timeout=<optimized out>, fdslen=<optimized out>)
    at poll_chk.c:27
#2  0x000000000051b17d in poll (__timeout=100, __nfds=<optimized out>, __fds=0x7fffab7fde40) at /usr/include/x86_64-linux-gnu/bits/poll2.h:41
#3  cPoller::Poll (this=this@entry=0x7fffab7fde40, TimeoutMs=TimeoutMs@entry=100) at tools.c:1446
#4  0x00000000004834e1 in cTSBuffer::Action (this=0x7fffe8001b80) at device.c:1760
#5  0x00000000005136f9 in cThread::StartThread (Thread=0x7fffe8001b80) at thread.c:262
#6  0x00007ffff79686ba in start_thread (arg=0x7fffab7fe700) at pthread_create.c:333
#7  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 36 (Thread 0x7fffabfff700 (LWP 32078)):
#0  0x00007ffff79719ff in __libc_send (fd=67, buf=buf@entry=0x7fffe4041370, n=n@entry=40, flags=flags@entry=32768)
    at ../sysdeps/unix/sysv/linux/x86_64/send.c:26
#1  0x00007ffff48f7f26 in cxSocket::write (this=0x7fffc80015b0, buffer=<optimized out>, size=size@entry=40, timeout_ms=timeout_ms@entry=-1, 
    more_data=more_data@entry=true) at cxsocket.c:98
#2  0x00007ffff48fdef2 in cLiveStreamer::sendStreamPacket (this=0x7fffdc023cb0, pkt=0x7fffabffee30) at streamer.c:364
#3  0x00007ffff48ff80d in cLiveStreamer::Action (this=0x7fffdc023cb0) at streamer.c:218
#4  0x00000000005136f9 in cThread::StartThread (Thread=0x7fffdc023cb0) at thread.c:262
#5  0x00007ffff79686ba in start_thread (arg=0x7fffabfff700) at pthread_create.c:333
#6  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 35 (Thread 0x7fffb27fc700 (LWP 32077)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000512eee in cCondWait::Wait (this=this@entry=0x7fffe89992b8, TimeoutMs=<optimized out>) at thread.c:71
#2  0x00000000004ee149 in cRingBuffer::WaitForGet (this=this@entry=0x7fffe8999250) at ringbuffer.c:74
#3  0x00000000004ee890 in cRingBufferLinear::Get (this=0x7fffe8999250, Count=@0x7fffb27fbd94: 0) at ringbuffer.c:366
#4  0x0000000000488abc in cTSBuffer::Get (this=0x7fffe8001b80, Available=Available@entry=0x0) at device.c:1783
#5  0x000000000048b6ff in cDvbDevice::GetTSPacket (this=0x910770, Data=@0x7fffb27fbe38: 0x0) at dvbdevice.c:1697
#6  0x0000000000488cb2 in cDevice::Action (this=0x910770) at device.c:1581
#7  0x00000000005136f9 in cThread::StartThread (Thread=0x910770) at thread.c:262
#8  0x00007ffff79686ba in start_thread (arg=0x7fffb27fc700) at pthread_create.c:333
#9  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 34 (Thread 0x7fffb2ffd700 (LWP 32076)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff63104ce in __poll_chk (fds=<optimized out>, nfds=<optimized out>, timeout=<optimized out>, fdslen=<optimized out>)
    at poll_chk.c:27
#2  0x000000000051b17d in poll (__timeout=-1, __nfds=<optimized out>, __fds=0x7fffc80015e8) at /usr/include/x86_64-linux-gnu/bits/poll2.h:41
#3  cPoller::Poll (this=this@entry=0x7fffc80015e8, TimeoutMs=TimeoutMs@entry=-1) at tools.c:1446
#4  0x00007ffff48f807a in cxSocket::read (this=this@entry=0x7fffc80015b0, buffer=buffer@entry=0x7fffb2ffce60, size=size@entry=4, 
---Type <return> to continue, or q <return> to quit--- 
    timeout_ms=timeout_ms@entry=-1) at cxsocket.c:128
#5  0x00007ffff48f52d4 in cVNSIClient::Action (this=0x7fffc8001530) at vnsiclient.c:91
#6  0x00000000005136f9 in cThread::StartThread (Thread=0x7fffc8001530) at thread.c:262
#7  0x00007ffff79686ba in start_thread (arg=0x7fffb2ffd700) at pthread_create.c:333
#8  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 33 (Thread 0x7fffb0bfb700 (LWP 31849)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff63104ce in __poll_chk (fds=<optimized out>, nfds=<optimized out>, timeout=<optimized out>, fdslen=<optimized out>)
    at poll_chk.c:27
#2  0x000000000051b17d in poll (__timeout=100, __nfds=<optimized out>, __fds=0x7fffb0bfae40) at /usr/include/x86_64-linux-gnu/bits/poll2.h:41
#3  cPoller::Poll (this=this@entry=0x7fffb0bfae40, TimeoutMs=TimeoutMs@entry=100) at tools.c:1446
#4  0x00000000004834e1 in cTSBuffer::Action (this=0x7fffd40008e0) at device.c:1760
#5  0x00000000005136f9 in cThread::StartThread (Thread=0x7fffd40008e0) at thread.c:262
#6  0x00007ffff79686ba in start_thread (arg=0x7fffb0bfb700) at pthread_create.c:333
#7  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 32 (Thread 0x7fffa9efd700 (LWP 31848)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000512eee in cCondWait::Wait (this=this@entry=0x7fffd40009e8, TimeoutMs=<optimized out>) at thread.c:71
#2  0x00000000004ee149 in cRingBuffer::WaitForGet (this=this@entry=0x7fffd4000980) at ringbuffer.c:74
#3  0x00000000004ee890 in cRingBufferLinear::Get (this=0x7fffd4000980, Count=@0x7fffa9efcd94: 0) at ringbuffer.c:366
#4  0x0000000000488abc in cTSBuffer::Get (this=0x7fffd40008e0, Available=Available@entry=0x0) at device.c:1783
#5  0x000000000048b6ff in cDvbDevice::GetTSPacket (this=0x909c20, Data=@0x7fffa9efce38: 0x0) at dvbdevice.c:1697
#6  0x0000000000488cb2 in cDevice::Action (this=0x909c20) at device.c:1581
#7  0x00000000005136f9 in cThread::StartThread (Thread=0x909c20) at thread.c:262
#8  0x00007ffff79686ba in start_thread (arg=0x7fffa9efd700) at pthread_create.c:333
#9  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 31 (Thread 0x7fffaabff700 (LWP 31847)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000512eee in cCondWait::Wait (this=this@entry=0x92dad8, TimeoutMs=<optimized out>) at thread.c:71
#2  0x00000000004ee149 in cRingBuffer::WaitForGet (this=this@entry=0x92da70) at ringbuffer.c:74
#3  0x00000000004ee890 in cRingBufferLinear::Get (this=0x92da70, Count=@0x7fffaabfee3c: 58280) at ringbuffer.c:366
#4  0x00000000004de03f in cRecorder::Action (this=0x950060) at recorder.c:125
#5  0x00000000005136f9 in cThread::StartThread (Thread=0x950190) at thread.c:262
#6  0x00007ffff79686ba in start_thread (arg=0x7fffaabff700) at pthread_create.c:333
#7  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 30 (Thread 0x7ffff36a9700 (LWP 31734)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff63104ce in __poll_chk (fds=<optimized out>, nfds=<optimized out>, timeout=<optimized out>, fdslen=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at poll_chk.c:27
#2  0x000000000051b17d in poll (__timeout=100, __nfds=<optimized out>, __fds=0x7ffff36a8e40) at /usr/include/x86_64-linux-gnu/bits/poll2.h:41
#3  cPoller::Poll (this=this@entry=0x7ffff36a8e40, TimeoutMs=TimeoutMs@entry=100) at tools.c:1446
#4  0x00000000004834e1 in cTSBuffer::Action (this=0x7fffc40008e0) at device.c:1760
#5  0x00000000005136f9 in cThread::StartThread (Thread=0x7fffc40008e0) at thread.c:262
#6  0x00007ffff79686ba in start_thread (arg=0x7ffff36a9700) at pthread_create.c:333
#7  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 29 (Thread 0x7fffb13fc700 (LWP 31733)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000512eee in cCondWait::Wait (this=this@entry=0x7fffc40009e8, TimeoutMs=<optimized out>) at thread.c:71
#2  0x00000000004ee149 in cRingBuffer::WaitForGet (this=this@entry=0x7fffc4000980) at ringbuffer.c:74
#3  0x00000000004ee890 in cRingBufferLinear::Get (this=0x7fffc4000980, Count=@0x7fffb13fbd94: 0) at ringbuffer.c:366
#4  0x0000000000488abc in cTSBuffer::Get (this=0x7fffc40008e0, Available=Available@entry=0x0) at device.c:1783
#5  0x000000000048b6ff in cDvbDevice::GetTSPacket (this=0x9030d0, Data=@0x7fffb13fbe38: 0x0) at dvbdevice.c:1697
#6  0x0000000000488cb2 in cDevice::Action (this=0x9030d0) at device.c:1581
#7  0x00000000005136f9 in cThread::StartThread (Thread=0x9030d0) at thread.c:262
#8  0x00007ffff79686ba in start_thread (arg=0x7fffb13fc700) at pthread_create.c:333
#9  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 28 (Thread 0x7fffb1bfd700 (LWP 31732)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000512eee in cCondWait::Wait (this=this@entry=0x951ba8, TimeoutMs=<optimized out>) at thread.c:71
#2  0x00000000004ee149 in cRingBuffer::WaitForGet (this=this@entry=0x951b40) at ringbuffer.c:74
#3  0x00000000004ee890 in cRingBufferLinear::Get (this=0x951b40, Count=@0x7fffb1bfce3c: 62040) at ringbuffer.c:366
#4  0x00000000004de03f in cRecorder::Action (this=0x94e430) at recorder.c:125
#5  0x00000000005136f9 in cThread::StartThread (Thread=0x94e560) at thread.c:262
#6  0x00007ffff79686ba in start_thread (arg=0x7fffb1bfd700) at pthread_create.c:333
#7  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 21 (Thread 0x7fffb37fe700 (LWP 31486)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff63104ce in __poll_chk (fds=<optimized out>, nfds=<optimized out>, timeout=<optimized out>, fdslen=<optimized out>)
    at poll_chk.c:27
#2  0x000000000051b17d in poll (__timeout=-1, __nfds=<optimized out>, __fds=0x7fffc8000d08) at /usr/include/x86_64-linux-gnu/bits/poll2.h:41
#3  cPoller::Poll (this=this@entry=0x7fffc8000d08, TimeoutMs=TimeoutMs@entry=-1) at tools.c:1446
#4  0x00007ffff48f807a in cxSocket::read (this=this@entry=0x7fffc8000cd0, buffer=buffer@entry=0x7fffb37fde60, size=size@entry=4, 
    timeout_ms=timeout_ms@entry=-1) at cxsocket.c:128
#5  0x00007ffff48f52d4 in cVNSIClient::Action (this=0x7fffc8000c50) at vnsiclient.c:91
#6  0x00000000005136f9 in cThread::StartThread (Thread=0x7fffc8000c50) at thread.c:262
#7  0x00007ffff79686ba in start_thread (arg=0x7fffb37fe700) at pthread_create.c:333
#8  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
---Type <return> to continue, or q <return> to quit---

Thread 15 (Thread 0x7fffd27fc700 (LWP 31480)):
#0  0x00007ffff62c375d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff62f51a4 in usleep (useconds=useconds@entry=250000) at ../sysdeps/posix/usleep.c:32
#2  0x00007ffff490c726 in cVNSIStatus::Action (this=0x8cf780) at status.c:307
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x8cf780) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7fffd27fc700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 13 (Thread 0x7fffd37fe700 (LWP 31478)):
#0  0x00007ffff62f49e3 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff4901d4d in cVNSIServer::Action (this=0x8cf650) at vnsiserver.c:195
#2  0x00000000005136f9 in cThread::StartThread (Thread=0x8cf650) at thread.c:262
#3  0x00007ffff79686ba in start_thread (arg=0x7fffd37fe700) at pthread_create.c:333
#4  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 12 (Thread 0x7fffd3fff700 (LWP 31477)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000004f05b2 in poll (__timeout=1000, __nfds=6, __fds=0x7fffd3ffde10) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  cSectionHandler::Action (this=0x902900) at sections.c:184
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x902900) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7fffd3fff700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 11 (Thread 0x7ffff0ea4700 (LWP 31476)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00000000005130dc in cCondVar::TimedWait (this=this@entry=0x8fb498, Mutex=..., TimeoutMs=TimeoutMs@entry=1000) at thread.c:127
#2  0x000000000048e6b5 in cDvbTuner::Action (this=0x8fad10) at dvbdevice.c:1000
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x8fad10) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7ffff0ea4700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 10 (Thread 0x7ffff16a5700 (LWP 31474)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000004f05b2 in poll (__timeout=1000, __nfds=6, __fds=0x7ffff16a3e10) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  cSectionHandler::Action (this=0x9025c0) at sections.c:184
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x9025c0) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7ffff16a5700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 9 (Thread 0x7ffff1ea6700 (LWP 31473)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
---Type <return> to continue, or q <return> to quit---
#1  0x00000000005130dc in cCondVar::TimedWait (this=this@entry=0x8fa648, Mutex=..., TimeoutMs=TimeoutMs@entry=1000) at thread.c:127
#2  0x000000000048e6b5 in cDvbTuner::Action (this=0x8f9ec0) at dvbdevice.c:1000
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x8f9ec0) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7ffff1ea6700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7ffff26a7700 (LWP 31471)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000004f05b2 in poll (__timeout=1000, __nfds=6, __fds=0x7ffff26a5e10) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  cSectionHandler::Action (this=0x8b3020) at sections.c:184
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x8b3020) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7ffff26a7700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7ffff46ab700 (LWP 31470)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00000000005130dc in cCondVar::TimedWait (this=this@entry=0x8da448, Mutex=..., TimeoutMs=TimeoutMs@entry=1000) at thread.c:127
#2  0x000000000048e6b5 in cDvbTuner::Action (this=0x8d9cc0) at dvbdevice.c:1000
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x8d9cc0) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7ffff46ab700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7ffff2ea8700 (LWP 31468)):
#0  0x00007ffff62f2b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000004f05b2 in poll (__timeout=1000, __nfds=6, __fds=0x7ffff2ea6e10) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  cSectionHandler::Action (this=0x8a79b0) at sections.c:184
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x8a79b0) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7ffff2ea8700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7ffff3eaa700 (LWP 31467)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00000000005130dc in cCondVar::TimedWait (this=this@entry=0x8b2958, Mutex=..., TimeoutMs=TimeoutMs@entry=1000) at thread.c:127
#2  0x000000000048e6b5 in cDvbTuner::Action (this=0x8b21d0) at dvbdevice.c:1000
#3  0x00000000005136f9 in cThread::StartThread (Thread=0x8b21d0) at thread.c:262
#4  0x00007ffff79686ba in start_thread (arg=0x7ffff3eaa700) at pthread_create.c:333
#5  0x00007ffff62fe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7fe2740 (LWP 31453)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000512eee in cCondWait::Wait (this=this@entry=0x7fffffffdf70, TimeoutMs=TimeoutMs@entry=10) at thread.c:71
#2  0x0000000000512f46 in cCondWait::SleepMs (TimeoutMs=TimeoutMs@entry=10) at thread.c:60
---Type <return> to continue, or q <return> to quit---
#3  0x00000000005135ae in cThread::Cancel (this=this@entry=0x8cf780, WaitSeconds=WaitSeconds@entry=5) at thread.c:331
#4  0x00007ffff490c88d in cVNSIStatus::Shutdown (this=this@entry=0x8cf780) at status.c:56
#5  0x00007ffff49011f7 in cVNSIServer::~cVNSIServer (this=0x8cf650, __in_chrg=<optimized out>) at vnsiserver.c:86
#6  0x00007ffff49012e9 in cVNSIServer::~cVNSIServer (this=0x8cf650, __in_chrg=<optimized out>) at vnsiserver.c:89
#7  0x00007ffff48ea863 in cPluginVNSIServer::Stop (this=0x805110) at vnsi.c:107
#8  0x00000000004dca35 in cPluginManager::StopPlugins (this=this@entry=0x7fffffffe270) at plugin.c:500
#9  0x000000000046a9cf in main (argc=<optimized out>, argv=<optimized out>) at vdr.c:1463

Cheers,
Michael

**Comment by FernetMenta** [comment]
hmm, select is a standard posix function. on what system do you run vdr? hardware, os, etc
